<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Male</name>
   <tag></tag>
   <elementGuidId>04af2f53-bba1-4faf-a154-a5e8bc3436e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.vfb-span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='item-vfb-31']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a87aaa26-9e7f-4209-9f7c-febdd56fd6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-span</value>
      <webElementGuid>98bea036-6f6c-4940-9caf-0ec85db6294d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>c3472153-3c56-47f6-8cb9-c56cf71d8d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-vfb-31&quot;)/div[1]/span[@class=&quot;vfb-span&quot;]</value>
      <webElementGuid>02768805-fdde-4375-8ee3-28960332089d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-31']/div/span</value>
      <webElementGuid>362c3bd7-c17c-4295-9015-510a464212f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::span[1]</value>
      <webElementGuid>a93f4a65-c3fc-44a1-b048-cfd405c249cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[1]</value>
      <webElementGuid>ac2a7765-f7b7-408e-8bc6-485bee6d4413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/preceding::span[1]</value>
      <webElementGuid>611a0c17-7927-4dd3-a6a5-2f0ba82d0e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>d657da78-f9b9-472a-9d85-fc5a5646c673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Male' or . = 'Male')]</value>
      <webElementGuid>54106861-a218-40e4-a4a4-a8417096635e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
